### ISSUE TITLE
Include `eslint@7` in peer dependency range

### ISSUE THREAD

**Issue by SimenB** [testing-library/eslint-plugin-testing-library#193] opened 2020-07-05 22:07 UTC
https://github.com/testing-library/eslint-plugin-testing-library/blob/f9f499b38209df0cf42fabcbcaafed1fe15f31a7/package.json#L69-L71

**Comment by nickmccurdy** [comment] 2020-07-06 02:47
This seems to be a duplicate of #138 and it will be fixed by #139. Mind if I close this?

**Closed** 2020-07-06 07:57 UTC

**Comment by SimenB** [comment] 2020-07-06 09:46
Ah, didn't find that somehow when searching 👍

**Comment by Belco90** [comment] 2020-09-20 15:50
This has been finally released in [v3.9.0](https://github.com/testing-library/eslint-plugin-testing-library/releases/tag/v3.9.0) 🎉
