### ISSUE TITLE
prefer-wait-for: Cannot read property 'arguments' of null

### ISSUE THREAD

**Issue by AriPerkkio** [testing-library/eslint-plugin-testing-library#272] opened 2020-12-15 13:40 UTC
Hello, `prefer-wait-for` rule seems to crash in certain cases. This issue was spotted by automated CI run - it is not blocking my development or anything. ESlint rules should not crash in any condition since this makes all valid linting problems disappear. If this is a false flag please let me know.

https://github.com/AriPerkkio/eslint-remote-tester/runs/1551964310?check_suite_focus=true

Complete list of dependencies and `.eslintrc` is available at CI runs logs, steps `Run yarn list | grep eslint` and `Run yarn log --config ./plugin-configs/eslint-plugin-testing-library.config.js`.

```
eslint-plugin-testing-library@3.10.1
```

```
rules: {
    'testing-library/prefer-wait-for': 'error',
}
```

### Minimal repro:

```js
import { waitForElement } from '@testing-library/react';

global.waitForElement = waitForElement;
```

```
TypeError: Cannot read property 'arguments' of null Occurred while linting <text>:2
    at Object.fix (/home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint-plugin-testing-library/rules/prefer-wait-for.js:61:50)
```

<details>
  <summary>Crash reports from real projects</summary>

## Rule: prefer-wait-for
- Message: `Cannot read property 'arguments' of null Occurred while linting <text>:2`
- Path: `diondirza/rexr/test/test-utils.js`
- [Link](https://github.com/diondirza/rexr/blob/HEAD/test/test-utils.js#L2)

```js
import React from 'react';
import { fireEvent, render, waitForElement } from '@testing-library/react';
import { HelmetProvider } from 'react-helmet-async';
import { Router } from 'react-router-dom';
import { createBrowserHistory } from 'history';

import { GlobalProvider } from '@context';
```

```
TypeError: Cannot read property 'arguments' of null Occurred while linting <text>:2
    at Object.fix (/home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint-plugin-testing-library/rules/prefer-wait-for.js:61:50)
    at normalizeFixes (/home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint/lib/linter/report-translator.js:178:28)
    at /home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint/lib/linter/report-translator.js:347:49
    at Object.report (/home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint/lib/linter/linter.js:920:41)
    at reportWait (/home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint-plugin-testing-library/rules/prefer-wait-for.js:53:21)
    at /home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint-plugin-testing-library/rules/prefer-wait-for.js:97:36
    at Array.forEach (<anonymous>)
    at /home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint-plugin-testing-library/rules/prefer-wait-for.js:96:52
    at Array.forEach (<anonymous>)
    at /home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint-plugin-testing-library/rules/prefer-wait-for.js:95:26
```

## Rule: prefer-wait-for
- Message: `Cannot read property 'arguments' of null Occurred while linting <text>:18`
- Path: `gravitational/webapps/packages/design/src/utils/testing.tsx`
- [Link](https://github.com/gravitational/webapps/blob/HEAD/packages/design/src/utils/testing.tsx#L18)

```tsx
 * limitations under the License.
 */

import React from 'react';
import {
  render as testingRender,
  act,
  fireEvent,
  waitForElement,
} from '@testing-library/react';
```

```
TypeError: Cannot read property 'arguments' of null Occurred while linting <text>:18
    at Object.fix (/home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint-plugin-testing-library/rules/prefer-wait-for.js:61:50)
    at normalizeFixes (/home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint/lib/linter/report-translator.js:178:28)
    at /home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint/lib/linter/report-translator.js:347:49
    at Object.report (/home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint/lib/linter/linter.js:920:41)
    at reportWait (/home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint-plugin-testing-library/rules/prefer-wait-for.js:53:21)
    at /home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint-plugin-testing-library/rules/prefer-wait-for.js:97:36
    at Array.forEach (<anonymous>)
    at /home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint-plugin-testing-library/rules/prefer-wait-for.js:96:52
    at Array.forEach (<anonymous>)
    at /home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint-plugin-testing-library/rules/prefer-wait-for.js:95:26
```

## Rule: prefer-wait-for
- Message: `Cannot read property 'arguments' of null Occurred while linting <text>:2`
- Path: `faultable/wardex/src/setupTests.js`
- [Link](https://github.com/faultable/wardex/blob/HEAD/src/setupTests.js#L2)

```js
import React from 'react'
import {
  afterEach,
  render,
  cleanup,
  fireEvent,
  wait,
```

```
TypeError: Cannot read property 'arguments' of null Occurred while linting <text>:2
    at Object.fix (/home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint-plugin-testing-library/rules/prefer-wait-for.js:61:50)
    at normalizeFixes (/home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint/lib/linter/report-translator.js:178:28)
    at /home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint/lib/linter/report-translator.js:347:49
    at Object.report (/home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint/lib/linter/linter.js:920:41)
    at reportWait (/home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint-plugin-testing-library/rules/prefer-wait-for.js:53:21)
    at /home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint-plugin-testing-library/rules/prefer-wait-for.js:97:36
    at Array.forEach (<anonymous>)
    at /home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint-plugin-testing-library/rules/prefer-wait-for.js:96:52
    at Array.forEach (<anonymous>)
    at /home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint-plugin-testing-library/rules/prefer-wait-for.js:95:26
```

## Rule: prefer-wait-for
- Message: `Cannot read property 'arguments' of null Occurred while linting <text>:2`
- Path: `activewidgets/react/test/adapter/react.js`
- [Link](https://github.com/activewidgets/react/blob/HEAD/test/adapter/react.js#L2)

```js

import {render, fireEvent, wait, waitForElement} from '@testing-library/react';
import {h} from '@activewidgets/components';


export function mount(component, props){
    return render(h(component, props));
```

```
TypeError: Cannot read property 'arguments' of null Occurred while linting <text>:2
    at Object.fix (/home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint-plugin-testing-library/rules/prefer-wait-for.js:61:50)
    at normalizeFixes (/home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint/lib/linter/report-translator.js:178:28)
    at /home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint/lib/linter/report-translator.js:347:49
    at Object.report (/home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint/lib/linter/linter.js:920:41)
    at reportWait (/home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint-plugin-testing-library/rules/prefer-wait-for.js:53:21)
    at /home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint-plugin-testing-library/rules/prefer-wait-for.js:97:36
    at Array.forEach (<anonymous>)
    at /home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint-plugin-testing-library/rules/prefer-wait-for.js:96:52
    at Array.forEach (<anonymous>)
    at /home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint-plugin-testing-library/rules/prefer-wait-for.js:95:26
```

## Rule: prefer-wait-for
- Message: `Cannot read property 'arguments' of null Occurred while linting <text>:3`
- Path: `w-sr/React-Storybook-Game/src/setupTests.js`
- [Link](https://github.com/w-sr/React-Storybook-Game/blob/HEAD/src/setupTests.js#L3)

```js
import React from 'react';
import '@testing-library/jest-dom/extend-expect';
import { render, fireEvent, waitForElement } from '@testing-library/react';
import renderer from 'react-test-renderer';
import sinon from 'sinon';
import { act } from 'react-dom/test-utils';
import 'jest-styled-components';

```

```
TypeError: Cannot read property 'arguments' of null Occurred while linting <text>:3
    at Object.fix (/home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint-plugin-testing-library/rules/prefer-wait-for.js:61:50)
    at normalizeFixes (/home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint/lib/linter/report-translator.js:178:28)
    at /home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint/lib/linter/report-translator.js:347:49
    at Object.report (/home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint/lib/linter/linter.js:920:41)
    at reportWait (/home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint-plugin-testing-library/rules/prefer-wait-for.js:53:21)
    at /home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint-plugin-testing-library/rules/prefer-wait-for.js:97:36
    at Array.forEach (<anonymous>)
    at /home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint-plugin-testing-library/rules/prefer-wait-for.js:96:52
    at Array.forEach (<anonymous>)
    at /home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint-plugin-testing-library/rules/prefer-wait-for.js:95:26
```

## Rule: prefer-wait-for
- Message: `Cannot read property 'arguments' of null Occurred while linting <text>:20`
- Path: `sumup-oss/circuit-ui/src/util/test-utils.tsx`
- [Link](https://github.com/sumup-oss/circuit-ui/blob/HEAD/src/util/test-utils.tsx#L20)

```tsx
import React, { FunctionComponent } from 'react';
import { renderToStaticMarkup } from 'react-dom/server';
import '@testing-library/jest-dom/extend-expect';
import { configureAxe } from 'jest-axe';
import {
  render as renderTest,
  wait,
  act,
  RenderResult,
} from '@testing-library/react';
```

```
TypeError: Cannot read property 'arguments' of null Occurred while linting <text>:20
    at Object.fix (/home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint-plugin-testing-library/rules/prefer-wait-for.js:61:50)
    at normalizeFixes (/home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint/lib/linter/report-translator.js:178:28)
    at /home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint/lib/linter/report-translator.js:347:49
    at Object.report (/home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint/lib/linter/linter.js:920:41)
    at reportWait (/home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint-plugin-testing-library/rules/prefer-wait-for.js:53:21)
    at /home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint-plugin-testing-library/rules/prefer-wait-for.js:97:36
    at Array.forEach (<anonymous>)
    at /home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint-plugin-testing-library/rules/prefer-wait-for.js:96:52
    at Array.forEach (<anonymous>)
    at /home/runner/work/eslint-remote-tester/eslint-remote-tester/ci/node_modules/eslint-plugin-testing-library/rules/prefer-wait-for.js:95:26
```

</details>

**Comment by gndelia** [comment] 2020-12-15 13:45
Hi AriPerkkio , thanks for posting. How would the test usage look like? Just a regular

```ts
waitForElement(() => getByText('foo')) 
```

?

I wouldn't recommend storing the queries in the global space. You can always import `screen` and use them from there. In addition to that, you might want to use `waitFor` instead of `waitForElement` as `waitForElement` is [deprecated](https://testing-library.com/docs/dom-testing-library/api-async/#waitforelement-deprecated-use-find-queries-or-waitfor).

Either way, we could try to fix this scenario to prevent the suite from crashing

**Comment by AriPerkkio** [comment] 2020-12-15 13:55
I should have mentioned that the use case causing the crash might not be valid or recommended. I'm just testing stability of various community ESLint plugins and reporting the issues to plugin developers. This same issue could come up in completely valid case too. 

This is also crashing:
```js
import { waitForElement } from '@testing-library/react';

const renamedWaitForElement = waitForElement;
```

**Comment by Belco90** [comment] 2020-12-15 14:30
Hello Ari. Thanks for opening this issue. You are right: this scenario should cause any error. However, we are close to finish v4 of the plugin, which includes a huge refactor of all rules almost from the ground. I can confirm this case has been fixed on v4 as you can see here:
<img width="1322" alt="image" src="https://user-images.githubusercontent.com/2677072/102227878-5b4d6400-3eea-11eb-9d66-0109a7c28266.png">
So I would suggest to wait for this version meanwhile if this is only an extreme edge case to catch errors in the plugin.

**Comment by AriPerkkio** [comment] 2020-12-15 14:39
Thanks for the verification @Belco90. Feel free to close this issue. 

Once v4 is available in npm I'll include it to my weekly scheduled CI runs on [eslint-remote-tester](https://github.com/AriPerkkio/eslint-remote-tester).

**Comment by Belco90** [comment] 2020-12-15 14:45
Awesome! I think I'm gonna leave it open as I did with other issues solved on v4 until it gets released.

**Comment by Belco90** [comment] 2021-04-11 18:28
This should be fixed on v4.0.0

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/eslint-plugin-testing-library/v/4.0.0)
- [GitHub release](https://github.com/testing-library/eslint-plugin-testing-library/releases/tag/v4.0.0)

**Closed by Belco90** 2021-04-11 18:28 UTC
Labels: fixed on v4

**Comment by Belco90** [comment] 2021-04-14 10:09
Hey @AriPerkkio! I saw after releasing v4 of the plugin the badge for this ESLint plugin is green in your `eslint-remote-tester`! 🎉 

Would be fine to include such a badge in our README?

**Comment by AriPerkkio** [comment] 2021-04-14 11:00
Congratulations about v4! 🎉 

I was excited to see how it stands against heavy 6 hour tests - and it was perfect score with 0 crashes.
It was so fast that I'm even suspecting I've misconfigured the [`eslintrc`](https://github.com/AriPerkkio/eslint-remote-tester/blob/master/ci/plugin-configs/eslint-plugin-testing-library.config.js#L7-L36) 😄.
`[eslint-plugin-testing-library]: Repositories (14024/14496)`

Here are some comparisons from other plugins. The results are not 100% comparable but it provides some useful feedback about plugin's performance.
```
6 hour time limit, maximum of 14K repositories to test:
[eslint-plugin-unicorn]: Repositories (6101/14496)
[eslint-plugin-react]: Repositories (5823/14496)
[eslint-plugin-import]: Repositories (7830/14496)
[eslint-plugin-mocha]: Repositories (3198/14496) 😢 
[eslint-plugin-jest]: Repositories (12910/14496)
``` 

> Would be fine to include such a badge in our README?

Definitely!

If you are interested in keeping `master` branch of this repository stable I could help by setting up PR where `eslint-remote-tester` would be run in this repository. Some ESLint plugins are already doing this. See https://github.com/marketplace/actions/eslint-remote-tester-runner.

**Comment by MichaelDeBoey** [comment] 2021-04-14 11:20
@AriPerkkio Would it also be possible to have your workflows report automatically in our repo somehow? 🤔
Maybe with a restriction that it would only be possible from a certain bot (with permissions on this repo), so that it's not flagged as spam or something.

You're already running all tests, so CI would run a second time on this repo for no other reason than to report possible bugs to us.

Can you also provide us with the list of the other ESLint plugins that already use your action themselves please?

**Comment by AriPerkkio** [comment] 2021-04-14 12:12
>Would it also be possible to have your workflows report automatically in our repo somehow?

I'm not sure whether Github provides functionality for this. The workflow is currently utilizing octokit client for creating the issues. I'll need to look into octokit's documentation - PRs to `eslint-remote-tester-run-action` are also welcome. 👍 

> so CI would run a second time on this repo for no other reason than to report possible bugs to us.

Note that `eslint-remote-tester` is running against the latest published release. It would be ideal if plugins would caught these issues even before publishing their release. Running against latest `master` is easiest from the plugin repositories themselves.

So far `eslint-plugin-unicorn`, `eslint-plugin-jest-dom` and `eslint-plugin-knex(?)` are running tests in their repositories. There is an open PR for `eslint-plugin-react` too. I haven't really advertised this tool much.

**Comment by MichaelDeBoey** [comment] 2021-04-14 13:06
> Note that `eslint-remote-tester` is running against the latest published release. It would be ideal if plugins would caught these issues even before publishing their release. Running against latest `master` is easiest from the plugin repositories themselves.

@AriPerkkio Since this package is using `semantic-release`, everything that's pushed to `main` will also be released.

Running these smoke tests in this repo will also result in a 6 hour run for each push to `main`.

We would also have to update the `repositories.json` ourselves, which will become outdated really quickly.  
Since you're already doing all this hard work, I think we could all benefit from that work without doing it twice.

**Comment by Belco90** [comment] 2021-04-14 13:18
It would be interesting to run this check to have some insights about the plugin, but we shouldn't block any package release because of this check.

**Comment by MichaelDeBoey** [comment] 2021-04-14 13:28
That's why I think it would be better to have this run in the original `eslint-remote-tester` repo and create an issue in this repository whenever there will be an error found.

Having this as a bot would be the way to go I think, as that way we can give/revoke permissions.

**Comment by AriPerkkio** [comment] 2021-04-14 13:52
Good points @MichaelDeBoey. Let's keep running the tests in `eslint-remote-tester` repository and check if the bot could post results in this project. 

I would imagine something like `repository-for-results: testing-library/eslint-plugin-testing-library` option for `eslint-remote-tester-run-action` setup. And possibly some other fields for selecting/authenticating the bot.

**Comment by Belco90** [comment] 2021-04-14 14:22
Thanks for your help @AriPerkkio! I'll include the badge in the following days. Probably we can move the reporting from `eslint-remote-tester` to a new discussion.

**Comment by Belco90** [comment] 2021-04-14 14:24
@AriPerkkio I forgot to mention: another possibility would be running `eslint-remote-tester-runner` within this project without blocking the CI at all, that's up to us 😄 . So every time we release a new version, we trigger the remote tester runner in parallel and leave it doing its thing to get the report when gets finished. Is that possible? I guess so right?

**Comment by AriPerkkio** [comment] 2021-04-14 16:13
That's definitely possible and even better option than waiting for my weekly scheduled tests to trigger. You wouldn't have to wait 7 days for getting the latest results.

There is of course this:

> We would also have to update/maintain the `repositories.json` & `eslint-remote-tester.config.js` files ourselves

... but it is not really that much of a work. I haven't updated my `repositories.json` in a long time: https://github.com/AriPerkkio/eslint-remote-tester/commits/master/configs/repositories.json

`eslint-remote-tester` will simply skip a repository in case it cannot clone it, e.g. when it encounters a repository which has been made private. Even the current `repositories.json` contains some private repositories. 

Also consider the case where you make a breaking change or add new rule. This change would have to be made into `eslint-remote-tester`'s `eslintrc` too. It would be easier if the configuration lived in same repository as the plugin. 

But as said both options are possible, it is up to you to decide which way to go.

**Comment by MichaelDeBoey** [comment] 2021-04-14 17:00
@AriPerkkio We can start with the weekly triggered tests on your repo for now and maybe manually putting all errors in an issue here I think.

We can discuss this maybe even further in an issue/discussion on your repo so we don't hijack this issue any further?
